morpho-org/morpho-optimizers-rewards

- distribution/merkleTree/currentDistribution.json
- src/ages/age-one/script/unclaimedTokens.ts
- src/ages/ages.ts
- src/utils/getUserRewards.ts
- test/ageOne/epochThree.test.ts
> feat(epochs)!: handle rewards if root is not yet updated

- subgraph/schema.graphql
- subgraph/src/indexes.ts
- subgraph/src/mapping-internal.ts
- subgraph/src/mapping/morpho-compound.ts
- subgraph/subgraph.yaml
> feat(subgraph)!: allow subgraph to be defined on aave and compound

- src/utils/getUserRewards.ts
> feat(userRewards): add root to claimData

- src/ages/age-one/index.ts
- src/utils/getUserRewards.ts
- test/ageOne/epochOne.test.ts
- test/ageOne/epochThree.test.ts
- test/ageOne/epochTwo.test.ts
The overall code is very dense and makes it hard to read. No spaces between functions, exports, or between blocks. Moreover, this pattern is not followed everywhere even in a single file. I suggest adding spaces to make it more readable.
> Refactor and thoughts

- package.json
- src/scripts/getUserRewards.ts
> refactor(script): move getUserRewards script

- distribution/age2/epoch1/marketsEmission.json
- src/ages/ages.ts
- subgraph/src/constants/endTimestamps.ts
- subgraph/src/distributions.ts
- fix mistake in end timestamp of age 2 epoch 1
> fix:  fix age2 epoch 1 distribution

- LICENSE
> fix(license): edit license author

- distribution/age2/epoch1/marketsEmission.json
- distribution/age2/epoch2/marketsEmission.json
- distribution/age2/epoch3/marketsEmission.json
- src/ages/distributions/ageTwoDistribution.ts
- The distribution was returning a market size in usd for age 2
> fix(distribution): fix usd instead of underlying

- distribution/age1/epoch1/usersDistribution.json
- distribution/age1/epoch2/usersDistribution.json
- distribution/age1/epoch3/usersDistribution.json
- distribution/age2/epoch1/usersDistribution.json
- distribution/age2/epoch2/usersDistribution.json
- distribution/age3/epoch1/marketsEmission.json
- src/ages/ages.ts
- subgraph/src/constants/endTimestamps.ts
- subgraph/src/constants/getAgeAndEpoch.ts
- subgraph/src/constants/startTimestamps.ts
- subgraph/src/distributions.ts
- compute the distribution at the snapshot block for age3-epoch1
- update the subgraph
> 🚀  Age 3 - Epoch 1 market emission

- src/ages/ages.ts
> feat(age2-epoch2): add end block

- src/vaults/Distributor.ts
- src/vaults/script/distribute.ts
- The batch was transferring all the merkle tree amount distributed through all epochs without taking into account already claimed amount
- The fix is to check the claimed amount and do `total - claimed` computation
> Fix faults batch transaction amount transferred

- distribution/age3/epoch1/marketsEmission.json
- src/ages/distributions/MarketsEmission.ts
- src/ages/distributions/index.ts
- src/scripts/computeMarketsEmissions.ts
- test/marketsDistribution.test.ts
Adding the snapshotProposal to the marketEmission if it exists.
> 🔧  add snapshotProposal

- .env.example
- src/ages/ages.ts
- src/ages/ages.types.ts
- src/config.ts
- src/scripts/computeUsersDistributions.ts
- src/utils/getUserRewards.ts
- test/ageOne/epochOne.test.ts
- test/ageOne/epochThree.test.ts
- test/ageOne/epochTwo.test.ts
- test/ageTwo/userDistribution.test.ts
- test/graph.test.ts
- add `SUBGRAPH_URL` env variable dependency
> feat: use env variable for subgraph endpoint

- src/constants/mechanismUpgrade.ts
- src/scripts/computeUsersDistributions.ts
- src/scripts/getUserRewards.ts
- src/utils/getUserBalances.ts
- src/utils/getUserRewards.ts
- src/utils/graph/getGraphBalances/balances.types.ts
- src/utils/graph/getGraphBalances/graphBalances.formater.ts
- src/utils/index.ts
- test/graph.test.ts
- test/userDistribution.test.ts
- Adapt the scripts for the distribution mechanism V2 #65
> Distribution mechanism V2: script update

- src/scripts/getUserRewards.ts
- src/utils/accumulatedEmission.ts
- test/userDistribution.test.ts
- Adding the test: Should distribute the correct number of tokens per market
Fixes: #23
> Add market specific data and tests

- .gitignore
- src/ages/distributions/Proofs.ts
- src/ages/distributions/UsersDistribution.ts
- src/scripts/computeUsersDistributions.ts
- src/scripts/getMarketsDistribution.ts
- src/scripts/getUserRewards.ts
- src/utils/StorageService.ts
- src/utils/accumulatedEmission.ts
- src/utils/computeUsersDistributions.ts
- src/utils/getCurrentOnChainDistribution.ts
- src/utils/getEpochMarketsDistribution.ts
- src/utils/getUserBalances.ts
- src/utils/getUserRewards.ts
- src/vaults/ProofsFetcher.ts
- src/vaults/script/distribute.ts
- test/marketsDistribution.test.ts
- test/marketsEmission.test.ts
- test/userDistribution.test.ts
- test/vaults/utils.ts
- test/vaults/vaults.test.ts
Abstract FS to StorageService.
> feat: Abstract FS read/write to StorageService

- src/constants/mechanismUpgrade.ts
- src/utils/getUserRewards.ts
- src/utils/graph/getGraphBalances/fetch.ts
- src/utils/graph/getGraphBalances/graphBalances.formater.ts
- src/utils/graph/getGraphBalances/graphBalances.formatter.ts
- src/utils/graph/getGraphBalances/index.ts
- test/marketsDistribution.test.ts
- fix markets without snapshots
> fix(mechanismV2): dump snapshot & tests

- distribution/age3/epoch3/marketsEmission.json
- src/ages/ages.data.json
- src/scripts/generateGraphEmissions.ts
- subgraph/src/ipfs.ts
- Snapshot vote here: [0x2c10391797a45353092ed220f41411d18a1a1cf82ded0a8d68452619e46b273e](https://snapshot.org/#/gauges.morpho.eth/proposal/0x2c10391797a45353092ed220f41411d18a1a1cf82ded0a8d68452619e46b273e)
- run of `yarn markets:emissions --epoch age3-epoch3` with the snapshot block: 
- update of the subgraph with the new ipfs distribution file: <TODO>
> [Age3 Epoch3]: markets emission

- src/ages/ages.data.json
> feat(age3-epoch2): add blocks to ages data

- README.md
- package.json
- src/scripts/claim.ts
- src/utils/claim.ts
- yarn.lock
- create a script permitting users to claim directly from the CLI
Closes: #81
> feat(claim): add a script to claim the rewards

- src/ages/ages.data.json
- src/ages/ages.ts
- src/ages/distributions/ageFourDistribution/ageFourDistribution.ts
- src/ages/distributions/ageFourDistribution/marketsRepartition.ts
- src/ages/distributions/ageThreeDistribution.ts
- src/ages/distributions/ageTwoDistribution.ts
- src/ages/distributions/index.ts
- src/ages/distributions/markets.ts
- src/ages/distributions/weightedDistribution.ts
- src/utils/markets/fetchMarketsData.ts
- test/marketsEmission.test.ts
- first step of the #87 
- ext steps needs a snapshot block, one hour before the beginning of the epoch
> Age 4 configuration

- src/constants/mechanismUpgrade.ts
- subgraph/src/constants.ts
- subgraph/src/indexes.ts
- postpone the mechanism refactoring to an undefined date
- fix the `subgraph` with the error in the market emission key of the ipfs file
> subgraph issue

- src/ages/distributions/weightedDistribution.ts
- remove `marketEmission` declared twice in market emission script
> fix(distribution): remove duplicated value

- src/ages/distributions/ageFourDistribution/ageFourDistribution.ts
- src/utils/etherscan/blockFromTimestamp.ts
The fetch of the snapshot block could fail if it hadn't been emitted yet.
This PR improves the error message to retry the market computation.
> fix(distribution): Improve error message on failed fetch snapshot block

- src/ages/distributions/ageFourDistribution/ageFourDistribution.ts
- src/ages/distributions/ageOneDistribution.ts
- src/ages/distributions/ageThreeDistribution.ts
- src/ages/distributions/ageTwoDistribution.ts
Fetch initial timestamp one hour earlier if snapshot block missing.
> fix(distributions): Fetch timestamp block one hour earlier

- distribution/age1/epoch1/marketsEmission.json
- distribution/age1/epoch2/marketsEmission.json
- distribution/age1/epoch3/marketsEmission.json
- distribution/age2/epoch1/marketsEmission.json
- distribution/age2/epoch2/marketsEmission.json
- distribution/age2/epoch3/marketsEmission.json
- distribution/age3/epoch1/marketsEmission.json
- distribution/age3/epoch2/marketsEmission.json
- distribution/age3/epoch3/marketsEmission.json
- distribution/age4/epoch1/marketsEmission.json
- src/scripts/computeMarketsEmissions.ts
- src/utils/getEpochMarketsDistribution.ts
- format total emission with 18 decimals to have stg more readable
> feat(emissions): format total emission

- src/utils/getUserRewards.ts
Remove `require` in `getUserRewards` to avoid bugs in no-FS context.
> fix: remove require in getUserRewards

- src/ages/ages.data.json
- src/ages/ages.ts
- src/ages/distributions/ageSixDistribution/ageSixDistribution.ts
- src/ages/distributions/ageSixDistribution/marketsRepartition.ts
- src/ages/distributions/index.ts
- add the market emission following [this proposal](https://forum.morpho.org/t/mip-morpho-rewards-age-6/329)
> feat(age6): Configuration

- distribution/age6/epoch1/marketsEmission.json
- src/ages/ages.data.json
- subgraph/src/ipfs.ts
- run `yarn markets:emissions --epoch 12`
- run `yarn markets:emissions:subgraph`
> feat(age6): Markets emissions

- src/ages/ageEpochConfig.ts
- The distribution is not working on the build, since the files are js files
> fix(emission): remove `ts` extension

- src/ages/ageEpochConfig.ts
Fix `getUserRewards` which was dependent on unfinished epochs.
> fix(getUserRewards): fix require of non-finished epochs

- .github/workflows/compute-markets-emissions.yml
- .github/workflows/compute-users-distributions.yml
- Gitbug bot was not triggering a release
> fix(ci): change bot commit message
